<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Megan_Beaudry Coding exercise</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet" />
<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #303030; color: #cccccc; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; }
td.sourceCode { padding-left: 5px; }
pre, code { color: #cccccc; background-color: #303030; }
code > span.kw { color: #f0dfaf; } /* Keyword */
code > span.dt { color: #dfdfbf; } /* DataType */
code > span.dv { color: #dcdccc; } /* DecVal */
code > span.bn { color: #dca3a3; } /* BaseN */
code > span.fl { color: #c0bed1; } /* Float */
code > span.ch { color: #dca3a3; } /* Char */
code > span.st { color: #cc9393; } /* String */
code > span.co { color: #7f9f7f; } /* Comment */
code > span.ot { color: #efef8f; } /* Other */
code > span.al { color: #ffcfaf; } /* Alert */
code > span.fu { color: #efef8f; } /* Function */
code > span.er { color: #c3bf9f; } /* Error */
code > span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */
code > span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
code > span.sc { color: #dca3a3; } /* SpecialChar */
code > span.vs { color: #cc9393; } /* VerbatimString */
code > span.ss { color: #cc9393; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { } /* Variable */
code > span.cf { color: #f0dfaf; } /* ControlFlow */
code > span.op { color: #f0efd0; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
code > span.at { } /* Attribute */
code > span.do { color: #7f9f7f; } /* Documentation */
code > span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
code > span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
code > span.in { color: #7f9f7f; font-weight: bold; } /* Information */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' || rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="customstyles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->



<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_').toLowerCase();
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = false;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}


.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
  padding-left: 25px;
  text-indent: 0;
}

.tocify .list-group-item {
  border-radius: 0px;
}

.tocify-subheader {
  display: inline;
}
.tocify-subheader .tocify-item {
  font-size: 0.95em;
}

</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-inverse  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Lipp Lab Data Analysis Repository Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Analysis Exercises
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./MeganBeaudry_Coding.html">Coding-Beaudry</a>
    </li>
    <li>
      <a href="./MeganLott-coding.html">Coding-Lott</a>
    </li>
    <li>
      <a href="./WilliamNorfolk_Coding.html">Coding-Norfolk</a>
    </li>
    <li>
      <a href="./MeganBeaudry_TidyTuesday_index.html">TidyTuesday1-Beaudry</a>
    </li>
    <li>
      <a href="./MeganLott_TidyTuesday_index.html">TidyTuesday1-Lott</a>
    </li>
    <li>
      <a href="./WilliamNorfolk_TidyTuesday_index.html">TidyTuesday1-Norfolk</a>
    </li>
    <li>
      <a href="./MeganBeaudry_Visualization_index.html">Visualization-Beaudry</a>
    </li>
    <li>
      <a href="./MeganLott_Visualization_index.html">Visualization-Lott</a>
    </li>
    <li>
      <a href="./WilliamNorfolk_Visualization_index.html">Visualization-Norfolk</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Modeling
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="./MeganLott_Continuous_Outcome_Analysis.html">Continuous Outcome-Lott</a>
    </li>
    <li>
      <a href="./WilliamNorfolk_Continuous_Outcome_Analysis.html">Continuous Outcome-Norfolk</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://williamnorfolk.github.io/LabAnalysesRepository/">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Megan_Beaudry Coding exercise</h1>

</div>


<div id="loading-and-checking-data" class="section level1">
<h1><em>LOADING AND CHECKING DATA</em> <br></h1>
</div>
<div id="we-want-to-load-the-dslabs-package" class="section level1">
<h1>We want to load the dslabs package <br></h1>
</div>
<div id="also-now-loading-tidyverse-and-skimr-packages" class="section level1">
<h1>Also now loading tidyverse and skimr packages <br></h1>
</div>
<div id="load-the-gapminder-data-set" class="section level1">
<h1>Load the gapminder data set <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dslabs)</code></pre></div>
<pre><code>## Warning: package &#39;dslabs&#39; was built under R version 3.5.2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(tidyverse)</code></pre></div>
<pre><code>## ── Attaching packages ─────── tidyverse 1.2.1 ──</code></pre>
<pre><code>## ✔ ggplot2 3.1.1       ✔ purrr   0.3.2  
## ✔ tibble  2.1.1       ✔ dplyr   0.8.0.1
## ✔ tidyr   0.8.3       ✔ stringr 1.4.0  
## ✔ readr   1.3.1       ✔ forcats 0.4.0</code></pre>
<pre><code>## Warning: package &#39;ggplot2&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;tibble&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;tidyr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;purrr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;dplyr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;stringr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## Warning: package &#39;forcats&#39; was built under R version 3.5.2</code></pre>
<pre><code>## ── Conflicts ────────── tidyverse_conflicts() ──
## ✖ dplyr::filter() masks stats::filter()
## ✖ dplyr::lag()    masks stats::lag()</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(skimr)</code></pre></div>
<pre><code>## Warning: package &#39;skimr&#39; was built under R version 3.5.2</code></pre>
<pre><code>## 
## Attaching package: &#39;skimr&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:stats&#39;:
## 
##     filter</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">data</span>(<span class="st">&quot;gapminder&quot;</span>)</code></pre></div>
</div>
<div id="use-the-help-function-to-see-what-the-data-contains" class="section level1">
<h1>Use the help() function to see what the data contains <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">help</span>(gapminder)</code></pre></div>
<div id="the-dataset-contains-health-and-incomeoutcomes-for-184-country-from-1960-to-2016" class="section level2">
<h2>The dataset contains health and incomeoutcomes for 184 country from 1960 to 2016 <br></h2>
</div>
</div>
<div id="str---displays-basic-strucutual-info." class="section level1">
<h1>str - displays basic strucutual info. <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(gapminder)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    10545 obs. of  9 variables:
##  $ country         : Factor w/ 185 levels &quot;Albania&quot;,&quot;Algeria&quot;,..: 1 2 3 4 5 6 7 8 9 10 ...
##  $ year            : int  1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 ...
##  $ infant_mortality: num  115.4 148.2 208 NA 59.9 ...
##  $ life_expectancy : num  62.9 47.5 36 63 65.4 ...
##  $ fertility       : num  6.19 7.65 7.32 4.43 3.11 4.55 4.82 3.45 2.7 5.57 ...
##  $ population      : num  1636054 11124892 5270844 54681 20619075 ...
##  $ gdp             : num  NA 1.38e+10 NA NA 1.08e+11 ...
##  $ continent       : Factor w/ 5 levels &quot;Africa&quot;,&quot;Americas&quot;,..: 4 1 1 2 2 3 2 5 4 3 ...
##  $ region          : Factor w/ 22 levels &quot;Australia and New Zealand&quot;,..: 19 11 10 2 15 21 2 1 22 21 ...</code></pre>
<div id="the-nine-variables-of-this-dataset-are-country-year-infant_mortality-life_expectany-fertility-population-gdp-continent-region" class="section level2">
<h2>The nine variables of this dataset are: country, year, infant_mortality, life_expectany, fertility, population, gdp, continent, region <br></h2>
</div>
</div>
<div id="summary---statistical-summaries-of-selected-data.-type-of-data-shown-depends-on-class" class="section level1">
<h1>summary - statistical summaries of selected data. Type of data shown depends on class <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(gapminder)</code></pre></div>
<pre><code>##                 country           year      infant_mortality
##  Albania            :   57   Min.   :1960   Min.   :  1.50  
##  Algeria            :   57   1st Qu.:1974   1st Qu.: 16.00  
##  Angola             :   57   Median :1988   Median : 41.50  
##  Antigua and Barbuda:   57   Mean   :1988   Mean   : 55.31  
##  Argentina          :   57   3rd Qu.:2002   3rd Qu.: 85.10  
##  Armenia            :   57   Max.   :2016   Max.   :276.90  
##  (Other)            :10203                  NA&#39;s   :1453    
##  life_expectancy   fertility       population             gdp           
##  Min.   :13.20   Min.   :0.840   Min.   :3.124e+04   Min.   :4.040e+07  
##  1st Qu.:57.50   1st Qu.:2.200   1st Qu.:1.333e+06   1st Qu.:1.846e+09  
##  Median :67.54   Median :3.750   Median :5.009e+06   Median :7.794e+09  
##  Mean   :64.81   Mean   :4.084   Mean   :2.701e+07   Mean   :1.480e+11  
##  3rd Qu.:73.00   3rd Qu.:6.000   3rd Qu.:1.523e+07   3rd Qu.:5.540e+10  
##  Max.   :83.90   Max.   :9.220   Max.   :1.376e+09   Max.   :1.174e+13  
##                  NA&#39;s   :187     NA&#39;s   :185         NA&#39;s   :2972       
##     continent                region    
##  Africa  :2907   Western Asia   :1026  
##  Americas:2052   Eastern Africa : 912  
##  Asia    :2679   Western Africa : 912  
##  Europe  :2223   Caribbean      : 741  
##  Oceania : 684   South America  : 684  
##                  Southern Europe: 684  
##                  (Other)        :5586</code></pre>
</div>
<div id="glimpse---shows-data-frame-info-again-like-str-structural-info-only-now-in-a-form-easier-to-read" class="section level1">
<h1>glimpse - shows data frame info again (like str structural info) only now in a form easier to read <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">glimpse</span>(gapminder)</code></pre></div>
<pre><code>## Observations: 10,545
## Variables: 9
## $ country          &lt;fct&gt; Albania, Algeria, Angola, Antigua and Barbuda, …
## $ year             &lt;int&gt; 1960, 1960, 1960, 1960, 1960, 1960, 1960, 1960,…
## $ infant_mortality &lt;dbl&gt; 115.40, 148.20, 208.00, NA, 59.87, NA, NA, 20.3…
## $ life_expectancy  &lt;dbl&gt; 62.87, 47.50, 35.98, 62.97, 65.39, 66.86, 65.66…
## $ fertility        &lt;dbl&gt; 6.19, 7.65, 7.32, 4.43, 3.11, 4.55, 4.82, 3.45,…
## $ population       &lt;dbl&gt; 1636054, 11124892, 5270844, 54681, 20619075, 18…
## $ gdp              &lt;dbl&gt; NA, 13828152297, NA, NA, 108322326649, NA, NA, …
## $ continent        &lt;fct&gt; Europe, Africa, Africa, Americas, Americas, Asi…
## $ region           &lt;fct&gt; Southern Europe, Northern Africa, Middle Africa…</code></pre>
</div>
<div id="skim---shows-summary-statistics-like-summary-only-now-with-brief-histograms-details-on-missing-data-for-each-variable-and-as-much-other-information-as-possible-in-a-concise-form." class="section level1">
<h1>skim - shows summary statistics (like summary) only now with brief histograms, details on missing data for each variable, and as much other information as possible in a concise form. <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">skim</span>(gapminder)</code></pre></div>
<div data-pagedtable="false">
<script data-pagedtable-source type="application/json">
{"columns":[{"label":[""],"name":["_rn_"],"type":[""],"align":["left"]},{"label":["variable"],"name":[1],"type":["chr"],"align":["left"]},{"label":["type"],"name":[2],"type":["chr"],"align":["left"]},{"label":["stat"],"name":[3],"type":["chr"],"align":["left"]},{"label":["level"],"name":[4],"type":["chr"],"align":["left"]},{"label":["value"],"name":[5],"type":["dbl"],"align":["right"]},{"label":["formatted"],"name":[6],"type":["chr"],"align":["left"]}],"data":[{"1":"country","2":"factor","3":"missing","4":".all","5":"0.000000e+00","6":"0","_rn_":"1"},{"1":"country","2":"factor","3":"complete","4":".all","5":"1.054500e+04","6":"10545","_rn_":"2"},{"1":"country","2":"factor","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"3"},{"1":"country","2":"factor","3":"n_unique","4":".all","5":"1.850000e+02","6":"185","_rn_":"4"},{"1":"country","2":"factor","3":"top_counts","4":"Albania","5":"5.700000e+01","6":"Alb: 57","_rn_":"5"},{"1":"country","2":"factor","3":"top_counts","4":"Algeria","5":"5.700000e+01","6":"Alg: 57","_rn_":"6"},{"1":"country","2":"factor","3":"top_counts","4":"Angola","5":"5.700000e+01","6":"Ang: 57","_rn_":"7"},{"1":"country","2":"factor","3":"top_counts","4":"Antigua and Barbuda","5":"5.700000e+01","6":"Ant: 57","_rn_":"8"},{"1":"country","2":"factor","3":"top_counts","4":"Argentina","5":"5.700000e+01","6":"Arg: 57","_rn_":"9"},{"1":"country","2":"factor","3":"top_counts","4":"Armenia","5":"5.700000e+01","6":"Arm: 57","_rn_":"10"},{"1":"country","2":"factor","3":"top_counts","4":"Aruba","5":"5.700000e+01","6":"Aru: 57","_rn_":"11"},{"1":"country","2":"factor","3":"top_counts","4":"Australia","5":"5.700000e+01","6":"Aus: 57","_rn_":"12"},{"1":"country","2":"factor","3":"top_counts","4":"Austria","5":"5.700000e+01","6":"Aus: 57","_rn_":"13"},{"1":"country","2":"factor","3":"top_counts","4":"Azerbaijan","5":"5.700000e+01","6":"Aze: 57","_rn_":"14"},{"1":"country","2":"factor","3":"top_counts","4":"Bahamas","5":"5.700000e+01","6":"Bah: 57","_rn_":"15"},{"1":"country","2":"factor","3":"top_counts","4":"Bahrain","5":"5.700000e+01","6":"Bah: 57","_rn_":"16"},{"1":"country","2":"factor","3":"top_counts","4":"Bangladesh","5":"5.700000e+01","6":"Ban: 57","_rn_":"17"},{"1":"country","2":"factor","3":"top_counts","4":"Barbados","5":"5.700000e+01","6":"Bar: 57","_rn_":"18"},{"1":"country","2":"factor","3":"top_counts","4":"Belarus","5":"5.700000e+01","6":"Bel: 57","_rn_":"19"},{"1":"country","2":"factor","3":"top_counts","4":"Belgium","5":"5.700000e+01","6":"Bel: 57","_rn_":"20"},{"1":"country","2":"factor","3":"top_counts","4":"Belize","5":"5.700000e+01","6":"Bel: 57","_rn_":"21"},{"1":"country","2":"factor","3":"top_counts","4":"Benin","5":"5.700000e+01","6":"Ben: 57","_rn_":"22"},{"1":"country","2":"factor","3":"top_counts","4":"Bhutan","5":"5.700000e+01","6":"Bhu: 57","_rn_":"23"},{"1":"country","2":"factor","3":"top_counts","4":"Bolivia","5":"5.700000e+01","6":"Bol: 57","_rn_":"24"},{"1":"country","2":"factor","3":"top_counts","4":"Bosnia and Herzegovina","5":"5.700000e+01","6":"Bos: 57","_rn_":"25"},{"1":"country","2":"factor","3":"top_counts","4":"Botswana","5":"5.700000e+01","6":"Bot: 57","_rn_":"26"},{"1":"country","2":"factor","3":"top_counts","4":"Brazil","5":"5.700000e+01","6":"Bra: 57","_rn_":"27"},{"1":"country","2":"factor","3":"top_counts","4":"Brunei","5":"5.700000e+01","6":"Bru: 57","_rn_":"28"},{"1":"country","2":"factor","3":"top_counts","4":"Bulgaria","5":"5.700000e+01","6":"Bul: 57","_rn_":"29"},{"1":"country","2":"factor","3":"top_counts","4":"Burkina Faso","5":"5.700000e+01","6":"Bur: 57","_rn_":"30"},{"1":"country","2":"factor","3":"top_counts","4":"Burundi","5":"5.700000e+01","6":"Bur: 57","_rn_":"31"},{"1":"country","2":"factor","3":"top_counts","4":"Cambodia","5":"5.700000e+01","6":"Cam: 57","_rn_":"32"},{"1":"country","2":"factor","3":"top_counts","4":"Cameroon","5":"5.700000e+01","6":"Cam: 57","_rn_":"33"},{"1":"country","2":"factor","3":"top_counts","4":"Canada","5":"5.700000e+01","6":"Can: 57","_rn_":"34"},{"1":"country","2":"factor","3":"top_counts","4":"Cape Verde","5":"5.700000e+01","6":"Cap: 57","_rn_":"35"},{"1":"country","2":"factor","3":"top_counts","4":"Central African Republic","5":"5.700000e+01","6":"Cen: 57","_rn_":"36"},{"1":"country","2":"factor","3":"top_counts","4":"Chad","5":"5.700000e+01","6":"Cha: 57","_rn_":"37"},{"1":"country","2":"factor","3":"top_counts","4":"Chile","5":"5.700000e+01","6":"Chi: 57","_rn_":"38"},{"1":"country","2":"factor","3":"top_counts","4":"China","5":"5.700000e+01","6":"Chi: 57","_rn_":"39"},{"1":"country","2":"factor","3":"top_counts","4":"Colombia","5":"5.700000e+01","6":"Col: 57","_rn_":"40"},{"1":"country","2":"factor","3":"top_counts","4":"Comoros","5":"5.700000e+01","6":"Com: 57","_rn_":"41"},{"1":"country","2":"factor","3":"top_counts","4":"Congo, Dem. Rep.","5":"5.700000e+01","6":"Con: 57","_rn_":"42"},{"1":"country","2":"factor","3":"top_counts","4":"Congo, Rep.","5":"5.700000e+01","6":"Con: 57","_rn_":"43"},{"1":"country","2":"factor","3":"top_counts","4":"Costa Rica","5":"5.700000e+01","6":"Cos: 57","_rn_":"44"},{"1":"country","2":"factor","3":"top_counts","4":"Cote d'Ivoire","5":"5.700000e+01","6":"Cot: 57","_rn_":"45"},{"1":"country","2":"factor","3":"top_counts","4":"Croatia","5":"5.700000e+01","6":"Cro: 57","_rn_":"46"},{"1":"country","2":"factor","3":"top_counts","4":"Cuba","5":"5.700000e+01","6":"Cub: 57","_rn_":"47"},{"1":"country","2":"factor","3":"top_counts","4":"Cyprus","5":"5.700000e+01","6":"Cyp: 57","_rn_":"48"},{"1":"country","2":"factor","3":"top_counts","4":"Czech Republic","5":"5.700000e+01","6":"Cze: 57","_rn_":"49"},{"1":"country","2":"factor","3":"top_counts","4":"Denmark","5":"5.700000e+01","6":"Den: 57","_rn_":"50"},{"1":"country","2":"factor","3":"top_counts","4":"Djibouti","5":"5.700000e+01","6":"Dji: 57","_rn_":"51"},{"1":"country","2":"factor","3":"top_counts","4":"Dominican Republic","5":"5.700000e+01","6":"Dom: 57","_rn_":"52"},{"1":"country","2":"factor","3":"top_counts","4":"Ecuador","5":"5.700000e+01","6":"Ecu: 57","_rn_":"53"},{"1":"country","2":"factor","3":"top_counts","4":"Egypt","5":"5.700000e+01","6":"Egy: 57","_rn_":"54"},{"1":"country","2":"factor","3":"top_counts","4":"El Salvador","5":"5.700000e+01","6":"El : 57","_rn_":"55"},{"1":"country","2":"factor","3":"top_counts","4":"Equatorial Guinea","5":"5.700000e+01","6":"Equ: 57","_rn_":"56"},{"1":"country","2":"factor","3":"top_counts","4":"Eritrea","5":"5.700000e+01","6":"Eri: 57","_rn_":"57"},{"1":"country","2":"factor","3":"top_counts","4":"Estonia","5":"5.700000e+01","6":"Est: 57","_rn_":"58"},{"1":"country","2":"factor","3":"top_counts","4":"Ethiopia","5":"5.700000e+01","6":"Eth: 57","_rn_":"59"},{"1":"country","2":"factor","3":"top_counts","4":"Fiji","5":"5.700000e+01","6":"Fij: 57","_rn_":"60"},{"1":"country","2":"factor","3":"top_counts","4":"Finland","5":"5.700000e+01","6":"Fin: 57","_rn_":"61"},{"1":"country","2":"factor","3":"top_counts","4":"France","5":"5.700000e+01","6":"Fra: 57","_rn_":"62"},{"1":"country","2":"factor","3":"top_counts","4":"French Polynesia","5":"5.700000e+01","6":"Fre: 57","_rn_":"63"},{"1":"country","2":"factor","3":"top_counts","4":"Gabon","5":"5.700000e+01","6":"Gab: 57","_rn_":"64"},{"1":"country","2":"factor","3":"top_counts","4":"Gambia","5":"5.700000e+01","6":"Gam: 57","_rn_":"65"},{"1":"country","2":"factor","3":"top_counts","4":"Georgia","5":"5.700000e+01","6":"Geo: 57","_rn_":"66"},{"1":"country","2":"factor","3":"top_counts","4":"Germany","5":"5.700000e+01","6":"Ger: 57","_rn_":"67"},{"1":"country","2":"factor","3":"top_counts","4":"Ghana","5":"5.700000e+01","6":"Gha: 57","_rn_":"68"},{"1":"country","2":"factor","3":"top_counts","4":"Greece","5":"5.700000e+01","6":"Gre: 57","_rn_":"69"},{"1":"country","2":"factor","3":"top_counts","4":"Greenland","5":"5.700000e+01","6":"Gre: 57","_rn_":"70"},{"1":"country","2":"factor","3":"top_counts","4":"Grenada","5":"5.700000e+01","6":"Gre: 57","_rn_":"71"},{"1":"country","2":"factor","3":"top_counts","4":"Guatemala","5":"5.700000e+01","6":"Gua: 57","_rn_":"72"},{"1":"country","2":"factor","3":"top_counts","4":"Guinea","5":"5.700000e+01","6":"Gui: 57","_rn_":"73"},{"1":"country","2":"factor","3":"top_counts","4":"Guinea-Bissau","5":"5.700000e+01","6":"Gui: 57","_rn_":"74"},{"1":"country","2":"factor","3":"top_counts","4":"Guyana","5":"5.700000e+01","6":"Guy: 57","_rn_":"75"},{"1":"country","2":"factor","3":"top_counts","4":"Haiti","5":"5.700000e+01","6":"Hai: 57","_rn_":"76"},{"1":"country","2":"factor","3":"top_counts","4":"Honduras","5":"5.700000e+01","6":"Hon: 57","_rn_":"77"},{"1":"country","2":"factor","3":"top_counts","4":"Hong Kong, China","5":"5.700000e+01","6":"Hon: 57","_rn_":"78"},{"1":"country","2":"factor","3":"top_counts","4":"Hungary","5":"5.700000e+01","6":"Hun: 57","_rn_":"79"},{"1":"country","2":"factor","3":"top_counts","4":"Iceland","5":"5.700000e+01","6":"Ice: 57","_rn_":"80"},{"1":"country","2":"factor","3":"top_counts","4":"India","5":"5.700000e+01","6":"Ind: 57","_rn_":"81"},{"1":"country","2":"factor","3":"top_counts","4":"Indonesia","5":"5.700000e+01","6":"Ind: 57","_rn_":"82"},{"1":"country","2":"factor","3":"top_counts","4":"Iran","5":"5.700000e+01","6":"Ira: 57","_rn_":"83"},{"1":"country","2":"factor","3":"top_counts","4":"Iraq","5":"5.700000e+01","6":"Ira: 57","_rn_":"84"},{"1":"country","2":"factor","3":"top_counts","4":"Ireland","5":"5.700000e+01","6":"Ire: 57","_rn_":"85"},{"1":"country","2":"factor","3":"top_counts","4":"Israel","5":"5.700000e+01","6":"Isr: 57","_rn_":"86"},{"1":"country","2":"factor","3":"top_counts","4":"Italy","5":"5.700000e+01","6":"Ita: 57","_rn_":"87"},{"1":"country","2":"factor","3":"top_counts","4":"Jamaica","5":"5.700000e+01","6":"Jam: 57","_rn_":"88"},{"1":"country","2":"factor","3":"top_counts","4":"Japan","5":"5.700000e+01","6":"Jap: 57","_rn_":"89"},{"1":"country","2":"factor","3":"top_counts","4":"Jordan","5":"5.700000e+01","6":"Jor: 57","_rn_":"90"},{"1":"country","2":"factor","3":"top_counts","4":"Kazakhstan","5":"5.700000e+01","6":"Kaz: 57","_rn_":"91"},{"1":"country","2":"factor","3":"top_counts","4":"Kenya","5":"5.700000e+01","6":"Ken: 57","_rn_":"92"},{"1":"country","2":"factor","3":"top_counts","4":"Kiribati","5":"5.700000e+01","6":"Kir: 57","_rn_":"93"},{"1":"country","2":"factor","3":"top_counts","4":"Kuwait","5":"5.700000e+01","6":"Kuw: 57","_rn_":"94"},{"1":"country","2":"factor","3":"top_counts","4":"Kyrgyz Republic","5":"5.700000e+01","6":"Kyr: 57","_rn_":"95"},{"1":"country","2":"factor","3":"top_counts","4":"Lao","5":"5.700000e+01","6":"Lao: 57","_rn_":"96"},{"1":"country","2":"factor","3":"top_counts","4":"Latvia","5":"5.700000e+01","6":"Lat: 57","_rn_":"97"},{"1":"country","2":"factor","3":"top_counts","4":"Lebanon","5":"5.700000e+01","6":"Leb: 57","_rn_":"98"},{"1":"country","2":"factor","3":"top_counts","4":"Lesotho","5":"5.700000e+01","6":"Les: 57","_rn_":"99"},{"1":"country","2":"factor","3":"top_counts","4":"Liberia","5":"5.700000e+01","6":"Lib: 57","_rn_":"100"},{"1":"country","2":"factor","3":"top_counts","4":"Libya","5":"5.700000e+01","6":"Lib: 57","_rn_":"101"},{"1":"country","2":"factor","3":"top_counts","4":"Lithuania","5":"5.700000e+01","6":"Lit: 57","_rn_":"102"},{"1":"country","2":"factor","3":"top_counts","4":"Luxembourg","5":"5.700000e+01","6":"Lux: 57","_rn_":"103"},{"1":"country","2":"factor","3":"top_counts","4":"Macao, China","5":"5.700000e+01","6":"Mac: 57","_rn_":"104"},{"1":"country","2":"factor","3":"top_counts","4":"Macedonia, FYR","5":"5.700000e+01","6":"Mac: 57","_rn_":"105"},{"1":"country","2":"factor","3":"top_counts","4":"Madagascar","5":"5.700000e+01","6":"Mad: 57","_rn_":"106"},{"1":"country","2":"factor","3":"top_counts","4":"Malawi","5":"5.700000e+01","6":"Mal: 57","_rn_":"107"},{"1":"country","2":"factor","3":"top_counts","4":"Malaysia","5":"5.700000e+01","6":"Mal: 57","_rn_":"108"},{"1":"country","2":"factor","3":"top_counts","4":"Maldives","5":"5.700000e+01","6":"Mal: 57","_rn_":"109"},{"1":"country","2":"factor","3":"top_counts","4":"Mali","5":"5.700000e+01","6":"Mal: 57","_rn_":"110"},{"1":"country","2":"factor","3":"top_counts","4":"Malta","5":"5.700000e+01","6":"Mal: 57","_rn_":"111"},{"1":"country","2":"factor","3":"top_counts","4":"Mauritania","5":"5.700000e+01","6":"Mau: 57","_rn_":"112"},{"1":"country","2":"factor","3":"top_counts","4":"Mauritius","5":"5.700000e+01","6":"Mau: 57","_rn_":"113"},{"1":"country","2":"factor","3":"top_counts","4":"Mexico","5":"5.700000e+01","6":"Mex: 57","_rn_":"114"},{"1":"country","2":"factor","3":"top_counts","4":"Micronesia, Fed. Sts.","5":"5.700000e+01","6":"Mic: 57","_rn_":"115"},{"1":"country","2":"factor","3":"top_counts","4":"Moldova","5":"5.700000e+01","6":"Mol: 57","_rn_":"116"},{"1":"country","2":"factor","3":"top_counts","4":"Mongolia","5":"5.700000e+01","6":"Mon: 57","_rn_":"117"},{"1":"country","2":"factor","3":"top_counts","4":"Montenegro","5":"5.700000e+01","6":"Mon: 57","_rn_":"118"},{"1":"country","2":"factor","3":"top_counts","4":"Morocco","5":"5.700000e+01","6":"Mor: 57","_rn_":"119"},{"1":"country","2":"factor","3":"top_counts","4":"Mozambique","5":"5.700000e+01","6":"Moz: 57","_rn_":"120"},{"1":"country","2":"factor","3":"top_counts","4":"Namibia","5":"5.700000e+01","6":"Nam: 57","_rn_":"121"},{"1":"country","2":"factor","3":"top_counts","4":"Nepal","5":"5.700000e+01","6":"Nep: 57","_rn_":"122"},{"1":"country","2":"factor","3":"top_counts","4":"Netherlands","5":"5.700000e+01","6":"Net: 57","_rn_":"123"},{"1":"country","2":"factor","3":"top_counts","4":"New Caledonia","5":"5.700000e+01","6":"New: 57","_rn_":"124"},{"1":"country","2":"factor","3":"top_counts","4":"New Zealand","5":"5.700000e+01","6":"New: 57","_rn_":"125"},{"1":"country","2":"factor","3":"top_counts","4":"Nicaragua","5":"5.700000e+01","6":"Nic: 57","_rn_":"126"},{"1":"country","2":"factor","3":"top_counts","4":"Niger","5":"5.700000e+01","6":"Nig: 57","_rn_":"127"},{"1":"country","2":"factor","3":"top_counts","4":"Nigeria","5":"5.700000e+01","6":"Nig: 57","_rn_":"128"},{"1":"country","2":"factor","3":"top_counts","4":"Norway","5":"5.700000e+01","6":"Nor: 57","_rn_":"129"},{"1":"country","2":"factor","3":"top_counts","4":"Oman","5":"5.700000e+01","6":"Oma: 57","_rn_":"130"},{"1":"country","2":"factor","3":"top_counts","4":"Pakistan","5":"5.700000e+01","6":"Pak: 57","_rn_":"131"},{"1":"country","2":"factor","3":"top_counts","4":"Panama","5":"5.700000e+01","6":"Pan: 57","_rn_":"132"},{"1":"country","2":"factor","3":"top_counts","4":"Papua New Guinea","5":"5.700000e+01","6":"Pap: 57","_rn_":"133"},{"1":"country","2":"factor","3":"top_counts","4":"Paraguay","5":"5.700000e+01","6":"Par: 57","_rn_":"134"},{"1":"country","2":"factor","3":"top_counts","4":"Peru","5":"5.700000e+01","6":"Per: 57","_rn_":"135"},{"1":"country","2":"factor","3":"top_counts","4":"Philippines","5":"5.700000e+01","6":"Phi: 57","_rn_":"136"},{"1":"country","2":"factor","3":"top_counts","4":"Poland","5":"5.700000e+01","6":"Pol: 57","_rn_":"137"},{"1":"country","2":"factor","3":"top_counts","4":"Portugal","5":"5.700000e+01","6":"Por: 57","_rn_":"138"},{"1":"country","2":"factor","3":"top_counts","4":"Puerto Rico","5":"5.700000e+01","6":"Pue: 57","_rn_":"139"},{"1":"country","2":"factor","3":"top_counts","4":"Qatar","5":"5.700000e+01","6":"Qat: 57","_rn_":"140"},{"1":"country","2":"factor","3":"top_counts","4":"Romania","5":"5.700000e+01","6":"Rom: 57","_rn_":"141"},{"1":"country","2":"factor","3":"top_counts","4":"Russia","5":"5.700000e+01","6":"Rus: 57","_rn_":"142"},{"1":"country","2":"factor","3":"top_counts","4":"Rwanda","5":"5.700000e+01","6":"Rwa: 57","_rn_":"143"},{"1":"country","2":"factor","3":"top_counts","4":"Samoa","5":"5.700000e+01","6":"Sam: 57","_rn_":"144"},{"1":"country","2":"factor","3":"top_counts","4":"Saudi Arabia","5":"5.700000e+01","6":"Sau: 57","_rn_":"145"},{"1":"country","2":"factor","3":"top_counts","4":"Senegal","5":"5.700000e+01","6":"Sen: 57","_rn_":"146"},{"1":"country","2":"factor","3":"top_counts","4":"Serbia","5":"5.700000e+01","6":"Ser: 57","_rn_":"147"},{"1":"country","2":"factor","3":"top_counts","4":"Seychelles","5":"5.700000e+01","6":"Sey: 57","_rn_":"148"},{"1":"country","2":"factor","3":"top_counts","4":"Sierra Leone","5":"5.700000e+01","6":"Sie: 57","_rn_":"149"},{"1":"country","2":"factor","3":"top_counts","4":"Singapore","5":"5.700000e+01","6":"Sin: 57","_rn_":"150"},{"1":"country","2":"factor","3":"top_counts","4":"Slovak Republic","5":"5.700000e+01","6":"Slo: 57","_rn_":"151"},{"1":"country","2":"factor","3":"top_counts","4":"Slovenia","5":"5.700000e+01","6":"Slo: 57","_rn_":"152"},{"1":"country","2":"factor","3":"top_counts","4":"Solomon Islands","5":"5.700000e+01","6":"Sol: 57","_rn_":"153"},{"1":"country","2":"factor","3":"top_counts","4":"South Africa","5":"5.700000e+01","6":"Sou: 57","_rn_":"154"},{"1":"country","2":"factor","3":"top_counts","4":"South Korea","5":"5.700000e+01","6":"Sou: 57","_rn_":"155"},{"1":"country","2":"factor","3":"top_counts","4":"Spain","5":"5.700000e+01","6":"Spa: 57","_rn_":"156"},{"1":"country","2":"factor","3":"top_counts","4":"Sri Lanka","5":"5.700000e+01","6":"Sri: 57","_rn_":"157"},{"1":"country","2":"factor","3":"top_counts","4":"St. Lucia","5":"5.700000e+01","6":"St.: 57","_rn_":"158"},{"1":"country","2":"factor","3":"top_counts","4":"St. Vincent and the Grenadines","5":"5.700000e+01","6":"St.: 57","_rn_":"159"},{"1":"country","2":"factor","3":"top_counts","4":"Sudan","5":"5.700000e+01","6":"Sud: 57","_rn_":"160"},{"1":"country","2":"factor","3":"top_counts","4":"Suriname","5":"5.700000e+01","6":"Sur: 57","_rn_":"161"},{"1":"country","2":"factor","3":"top_counts","4":"Swaziland","5":"5.700000e+01","6":"Swa: 57","_rn_":"162"},{"1":"country","2":"factor","3":"top_counts","4":"Sweden","5":"5.700000e+01","6":"Swe: 57","_rn_":"163"},{"1":"country","2":"factor","3":"top_counts","4":"Switzerland","5":"5.700000e+01","6":"Swi: 57","_rn_":"164"},{"1":"country","2":"factor","3":"top_counts","4":"Syria","5":"5.700000e+01","6":"Syr: 57","_rn_":"165"},{"1":"country","2":"factor","3":"top_counts","4":"Tajikistan","5":"5.700000e+01","6":"Taj: 57","_rn_":"166"},{"1":"country","2":"factor","3":"top_counts","4":"Tanzania","5":"5.700000e+01","6":"Tan: 57","_rn_":"167"},{"1":"country","2":"factor","3":"top_counts","4":"Thailand","5":"5.700000e+01","6":"Tha: 57","_rn_":"168"},{"1":"country","2":"factor","3":"top_counts","4":"Timor-Leste","5":"5.700000e+01","6":"Tim: 57","_rn_":"169"},{"1":"country","2":"factor","3":"top_counts","4":"Togo","5":"5.700000e+01","6":"Tog: 57","_rn_":"170"},{"1":"country","2":"factor","3":"top_counts","4":"Tonga","5":"5.700000e+01","6":"Ton: 57","_rn_":"171"},{"1":"country","2":"factor","3":"top_counts","4":"Trinidad and Tobago","5":"5.700000e+01","6":"Tri: 57","_rn_":"172"},{"1":"country","2":"factor","3":"top_counts","4":"Tunisia","5":"5.700000e+01","6":"Tun: 57","_rn_":"173"},{"1":"country","2":"factor","3":"top_counts","4":"Turkey","5":"5.700000e+01","6":"Tur: 57","_rn_":"174"},{"1":"country","2":"factor","3":"top_counts","4":"Turkmenistan","5":"5.700000e+01","6":"Tur: 57","_rn_":"175"},{"1":"country","2":"factor","3":"top_counts","4":"Uganda","5":"5.700000e+01","6":"Uga: 57","_rn_":"176"},{"1":"country","2":"factor","3":"top_counts","4":"Ukraine","5":"5.700000e+01","6":"Ukr: 57","_rn_":"177"},{"1":"country","2":"factor","3":"top_counts","4":"United Arab Emirates","5":"5.700000e+01","6":"Uni: 57","_rn_":"178"},{"1":"country","2":"factor","3":"top_counts","4":"United Kingdom","5":"5.700000e+01","6":"Uni: 57","_rn_":"179"},{"1":"country","2":"factor","3":"top_counts","4":"United States","5":"5.700000e+01","6":"Uni: 57","_rn_":"180"},{"1":"country","2":"factor","3":"top_counts","4":"Uruguay","5":"5.700000e+01","6":"Uru: 57","_rn_":"181"},{"1":"country","2":"factor","3":"top_counts","4":"Uzbekistan","5":"5.700000e+01","6":"Uzb: 57","_rn_":"182"},{"1":"country","2":"factor","3":"top_counts","4":"Vanuatu","5":"5.700000e+01","6":"Van: 57","_rn_":"183"},{"1":"country","2":"factor","3":"top_counts","4":"Venezuela","5":"5.700000e+01","6":"Ven: 57","_rn_":"184"},{"1":"country","2":"factor","3":"top_counts","4":"Vietnam","5":"5.700000e+01","6":"Vie: 57","_rn_":"185"},{"1":"country","2":"factor","3":"top_counts","4":"West Bank and Gaza","5":"5.700000e+01","6":"Wes: 57","_rn_":"186"},{"1":"country","2":"factor","3":"top_counts","4":"Yemen","5":"5.700000e+01","6":"Yem: 57","_rn_":"187"},{"1":"country","2":"factor","3":"top_counts","4":"Zambia","5":"5.700000e+01","6":"Zam: 57","_rn_":"188"},{"1":"country","2":"factor","3":"top_counts","4":"Zimbabwe","5":"5.700000e+01","6":"Zim: 57","_rn_":"189"},{"1":"country","2":"factor","3":"top_counts","4":"NA","5":"0.000000e+00","6":"NA: 0","_rn_":"190"},{"1":"country","2":"factor","3":"ordered","4":".all","5":"0.000000e+00","6":"FALSE","_rn_":"191"},{"1":"year","2":"integer","3":"missing","4":".all","5":"0.000000e+00","6":"0","_rn_":"192"},{"1":"year","2":"integer","3":"complete","4":".all","5":"1.054500e+04","6":"10545","_rn_":"193"},{"1":"year","2":"integer","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"194"},{"1":"year","2":"integer","3":"mean","4":".all","5":"1.988000e+03","6":"1988","_rn_":"195"},{"1":"year","2":"integer","3":"sd","4":".all","5":"1.645273e+01","6":"16.45","_rn_":"196"},{"1":"year","2":"integer","3":"p0","4":".all","5":"1.960000e+03","6":"1960","_rn_":"197"},{"1":"year","2":"integer","3":"p25","4":".all","5":"1.974000e+03","6":"1974","_rn_":"198"},{"1":"year","2":"integer","3":"p50","4":".all","5":"1.988000e+03","6":"1988","_rn_":"199"},{"1":"year","2":"integer","3":"p75","4":".all","5":"2.002000e+03","6":"2002","_rn_":"200"},{"1":"year","2":"integer","3":"p100","4":".all","5":"2.016000e+03","6":"2016","_rn_":"201"},{"1":"year","2":"integer","3":"hist","4":".all","5":"NA","6":"▇▇▇▇▇▇▇▇","_rn_":"202"},{"1":"infant_mortality","2":"numeric","3":"missing","4":".all","5":"1.453000e+03","6":"1453","_rn_":"203"},{"1":"infant_mortality","2":"numeric","3":"complete","4":".all","5":"9.092000e+03","6":"9092","_rn_":"204"},{"1":"infant_mortality","2":"numeric","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"205"},{"1":"infant_mortality","2":"numeric","3":"mean","4":".all","5":"5.530862e+01","6":"55.31","_rn_":"206"},{"1":"infant_mortality","2":"numeric","3":"sd","4":".all","5":"4.772805e+01","6":"47.73","_rn_":"207"},{"1":"infant_mortality","2":"numeric","3":"p0","4":".all","5":"1.500000e+00","6":"1.5","_rn_":"208"},{"1":"infant_mortality","2":"numeric","3":"p25","4":".all","5":"1.600000e+01","6":"16","_rn_":"209"},{"1":"infant_mortality","2":"numeric","3":"p50","4":".all","5":"4.150000e+01","6":"41.5","_rn_":"210"},{"1":"infant_mortality","2":"numeric","3":"p75","4":".all","5":"8.510000e+01","6":"85.1","_rn_":"211"},{"1":"infant_mortality","2":"numeric","3":"p100","4":".all","5":"2.769000e+02","6":"276.9","_rn_":"212"},{"1":"infant_mortality","2":"numeric","3":"hist","4":".all","5":"NA","6":"▇▃▂▂▁▁▁▁","_rn_":"213"},{"1":"life_expectancy","2":"numeric","3":"missing","4":".all","5":"0.000000e+00","6":"0","_rn_":"214"},{"1":"life_expectancy","2":"numeric","3":"complete","4":".all","5":"1.054500e+04","6":"10545","_rn_":"215"},{"1":"life_expectancy","2":"numeric","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"216"},{"1":"life_expectancy","2":"numeric","3":"mean","4":".all","5":"6.481162e+01","6":"64.81","_rn_":"217"},{"1":"life_expectancy","2":"numeric","3":"sd","4":".all","5":"1.067249e+01","6":"10.67","_rn_":"218"},{"1":"life_expectancy","2":"numeric","3":"p0","4":".all","5":"1.320000e+01","6":"13.2","_rn_":"219"},{"1":"life_expectancy","2":"numeric","3":"p25","4":".all","5":"5.750000e+01","6":"57.5","_rn_":"220"},{"1":"life_expectancy","2":"numeric","3":"p50","4":".all","5":"6.754000e+01","6":"67.54","_rn_":"221"},{"1":"life_expectancy","2":"numeric","3":"p75","4":".all","5":"7.300000e+01","6":"73","_rn_":"222"},{"1":"life_expectancy","2":"numeric","3":"p100","4":".all","5":"8.390000e+01","6":"83.9","_rn_":"223"},{"1":"life_expectancy","2":"numeric","3":"hist","4":".all","5":"NA","6":"▁▁▁▂▃▅▇▃","_rn_":"224"},{"1":"fertility","2":"numeric","3":"missing","4":".all","5":"1.870000e+02","6":"187","_rn_":"225"},{"1":"fertility","2":"numeric","3":"complete","4":".all","5":"1.035800e+04","6":"10358","_rn_":"226"},{"1":"fertility","2":"numeric","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"227"},{"1":"fertility","2":"numeric","3":"mean","4":".all","5":"4.083521e+00","6":"4.08","_rn_":"228"},{"1":"fertility","2":"numeric","3":"sd","4":".all","5":"2.027320e+00","6":"2.03","_rn_":"229"},{"1":"fertility","2":"numeric","3":"p0","4":".all","5":"8.400000e-01","6":"0.84","_rn_":"230"},{"1":"fertility","2":"numeric","3":"p25","4":".all","5":"2.200000e+00","6":"2.2","_rn_":"231"},{"1":"fertility","2":"numeric","3":"p50","4":".all","5":"3.750000e+00","6":"3.75","_rn_":"232"},{"1":"fertility","2":"numeric","3":"p75","4":".all","5":"6.000000e+00","6":"6","_rn_":"233"},{"1":"fertility","2":"numeric","3":"p100","4":".all","5":"9.220000e+00","6":"9.22","_rn_":"234"},{"1":"fertility","2":"numeric","3":"hist","4":".all","5":"NA","6":"▅▇▃▃▅▆▂▁","_rn_":"235"},{"1":"population","2":"numeric","3":"missing","4":".all","5":"1.850000e+02","6":"185","_rn_":"236"},{"1":"population","2":"numeric","3":"complete","4":".all","5":"1.036000e+04","6":"10360","_rn_":"237"},{"1":"population","2":"numeric","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"238"},{"1":"population","2":"numeric","3":"mean","4":".all","5":"2.701461e+07","6":"2.7e+07","_rn_":"239"},{"1":"population","2":"numeric","3":"sd","4":".all","5":"1.066649e+08","6":"1.1e+08","_rn_":"240"},{"1":"population","2":"numeric","3":"p0","4":".all","5":"3.123800e+04","6":"31238","_rn_":"241"},{"1":"population","2":"numeric","3":"p25","4":".all","5":"1.333486e+06","6":"1333486","_rn_":"242"},{"1":"population","2":"numeric","3":"p50","4":".all","5":"5.009043e+06","6":"5e+06","_rn_":"243"},{"1":"population","2":"numeric","3":"p75","4":".all","5":"1.523179e+07","6":"1.5e+07","_rn_":"244"},{"1":"population","2":"numeric","3":"p100","4":".all","5":"1.376049e+09","6":"1.4e+09","_rn_":"245"},{"1":"population","2":"numeric","3":"hist","4":".all","5":"NA","6":"▇▁▁▁▁▁▁▁","_rn_":"246"},{"1":"gdp","2":"numeric","3":"missing","4":".all","5":"2.972000e+03","6":"2972","_rn_":"247"},{"1":"gdp","2":"numeric","3":"complete","4":".all","5":"7.573000e+03","6":"7573","_rn_":"248"},{"1":"gdp","2":"numeric","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"249"},{"1":"gdp","2":"numeric","3":"mean","4":".all","5":"1.479544e+11","6":"1.5e+11","_rn_":"250"},{"1":"gdp","2":"numeric","3":"sd","4":".all","5":"6.979128e+11","6":"7e+11","_rn_":"251"},{"1":"gdp","2":"numeric","3":"p0","4":".all","5":"4.039513e+07","6":"4e+07","_rn_":"252"},{"1":"gdp","2":"numeric","3":"p25","4":".all","5":"1.845780e+09","6":"1.8e+09","_rn_":"253"},{"1":"gdp","2":"numeric","3":"p50","4":".all","5":"7.794215e+09","6":"7.8e+09","_rn_":"254"},{"1":"gdp","2":"numeric","3":"p75","4":".all","5":"5.539965e+10","6":"5.5e+10","_rn_":"255"},{"1":"gdp","2":"numeric","3":"p100","4":".all","5":"1.174422e+13","6":"1.2e+13","_rn_":"256"},{"1":"gdp","2":"numeric","3":"hist","4":".all","5":"NA","6":"▇▁▁▁▁▁▁▁","_rn_":"257"},{"1":"continent","2":"factor","3":"missing","4":".all","5":"0.000000e+00","6":"0","_rn_":"258"},{"1":"continent","2":"factor","3":"complete","4":".all","5":"1.054500e+04","6":"10545","_rn_":"259"},{"1":"continent","2":"factor","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"260"},{"1":"continent","2":"factor","3":"n_unique","4":".all","5":"5.000000e+00","6":"5","_rn_":"261"},{"1":"continent","2":"factor","3":"top_counts","4":"Africa","5":"2.907000e+03","6":"Afr: 2907","_rn_":"262"},{"1":"continent","2":"factor","3":"top_counts","4":"Asia","5":"2.679000e+03","6":"Asi: 2679","_rn_":"263"},{"1":"continent","2":"factor","3":"top_counts","4":"Europe","5":"2.223000e+03","6":"Eur: 2223","_rn_":"264"},{"1":"continent","2":"factor","3":"top_counts","4":"Americas","5":"2.052000e+03","6":"Ame: 2052","_rn_":"265"},{"1":"continent","2":"factor","3":"top_counts","4":"Oceania","5":"6.840000e+02","6":"Oce: 684","_rn_":"266"},{"1":"continent","2":"factor","3":"top_counts","4":"NA","5":"0.000000e+00","6":"NA: 0","_rn_":"267"},{"1":"continent","2":"factor","3":"ordered","4":".all","5":"0.000000e+00","6":"FALSE","_rn_":"268"},{"1":"region","2":"factor","3":"missing","4":".all","5":"0.000000e+00","6":"0","_rn_":"269"},{"1":"region","2":"factor","3":"complete","4":".all","5":"1.054500e+04","6":"10545","_rn_":"270"},{"1":"region","2":"factor","3":"n","4":".all","5":"1.054500e+04","6":"10545","_rn_":"271"},{"1":"region","2":"factor","3":"n_unique","4":".all","5":"2.200000e+01","6":"22","_rn_":"272"},{"1":"region","2":"factor","3":"top_counts","4":"Western Asia","5":"1.026000e+03","6":"Wes: 1026","_rn_":"273"},{"1":"region","2":"factor","3":"top_counts","4":"Eastern Africa","5":"9.120000e+02","6":"Eas: 912","_rn_":"274"},{"1":"region","2":"factor","3":"top_counts","4":"Western Africa","5":"9.120000e+02","6":"Wes: 912","_rn_":"275"},{"1":"region","2":"factor","3":"top_counts","4":"Caribbean","5":"7.410000e+02","6":"Car: 741","_rn_":"276"},{"1":"region","2":"factor","3":"top_counts","4":"South America","5":"6.840000e+02","6":"Sou: 684","_rn_":"277"},{"1":"region","2":"factor","3":"top_counts","4":"Southern Europe","5":"6.840000e+02","6":"Sou: 684","_rn_":"278"},{"1":"region","2":"factor","3":"top_counts","4":"Eastern Europe","5":"5.700000e+02","6":"Eas: 570","_rn_":"279"},{"1":"region","2":"factor","3":"top_counts","4":"Northern Europe","5":"5.700000e+02","6":"Nor: 570","_rn_":"280"},{"1":"region","2":"factor","3":"top_counts","4":"South-Eastern Asia","5":"5.700000e+02","6":"Sou: 570","_rn_":"281"},{"1":"region","2":"factor","3":"top_counts","4":"Central America","5":"4.560000e+02","6":"Cen: 456","_rn_":"282"},{"1":"region","2":"factor","3":"top_counts","4":"Middle Africa","5":"4.560000e+02","6":"Mid: 456","_rn_":"283"},{"1":"region","2":"factor","3":"top_counts","4":"Southern Asia","5":"4.560000e+02","6":"Sou: 456","_rn_":"284"},{"1":"region","2":"factor","3":"top_counts","4":"Western Europe","5":"3.990000e+02","6":"Wes: 399","_rn_":"285"},{"1":"region","2":"factor","3":"top_counts","4":"Eastern Asia","5":"3.420000e+02","6":"Eas: 342","_rn_":"286"},{"1":"region","2":"factor","3":"top_counts","4":"Northern Africa","5":"3.420000e+02","6":"Nor: 342","_rn_":"287"},{"1":"region","2":"factor","3":"top_counts","4":"Central Asia","5":"2.850000e+02","6":"Cen: 285","_rn_":"288"},{"1":"region","2":"factor","3":"top_counts","4":"Melanesia","5":"2.850000e+02","6":"Mel: 285","_rn_":"289"},{"1":"region","2":"factor","3":"top_counts","4":"Southern Africa","5":"2.850000e+02","6":"Sou: 285","_rn_":"290"},{"1":"region","2":"factor","3":"top_counts","4":"Northern America","5":"1.710000e+02","6":"Nor: 171","_rn_":"291"},{"1":"region","2":"factor","3":"top_counts","4":"Polynesia","5":"1.710000e+02","6":"Pol: 171","_rn_":"292"},{"1":"region","2":"factor","3":"top_counts","4":"Australia and New Zealand","5":"1.140000e+02","6":"Aus: 114","_rn_":"293"},{"1":"region","2":"factor","3":"top_counts","4":"Micronesia","5":"1.140000e+02","6":"Mic: 114","_rn_":"294"},{"1":"region","2":"factor","3":"top_counts","4":"NA","5":"0.000000e+00","6":"NA: 0","_rn_":"295"},{"1":"region","2":"factor","3":"ordered","4":".all","5":"0.000000e+00","6":"FALSE","_rn_":"296"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
<div id="class---what-type-of-fuction-is-gapminder" class="section level1">
<h1>class - what type of fuction is gapminder</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(gapminder)</code></pre></div>
<pre><code>## [1] &quot;data.frame&quot;</code></pre>
<p><br> <br> <br> #<em>PROCESSING DATA</em> <br> #Here the workflow diverges into a Tidyverse Exercise and a base R exercise. Tidyverse exercises are shown first <br></p>
<p><br> <br> <br> #<em>Tidyverse code and plotting</em> <br> #For tidyverse package use, we start a pipeline for gapminder data with %&gt;% (“then”) <br> #We then filter () the data for only those data whose country is Africa <br> #then select() only the variables infant_mortality, life_expectancy, population, and country to remain <br> #plotting with country by color reveals many African countries. We also see that 226 rows are omitted from the plot due to missing values<br> #We see the same negative correlation between infant mortality and life expectancy here as we do below with base R code <br></p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(continent <span class="op">==</span><span class="st"> &quot;Africa&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(infant_mortality, life_expectancy, population, country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(infant_mortality, life_expectancy, <span class="dt">col=</span> country))</code></pre></div>
<pre><code>## Warning: Removed 226 rows containing missing values (geom_point).</code></pre>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
<div id="repeat-for-plot-of-population-versus-life-expectancy" class="section level1">
<h1>Repeat for plot of population versus life expectancy <br></h1>
</div>
<div id="in-this-case-51-omissions-occur-due-to-no-population-variable-value" class="section level1">
<h1>In this case, 51 omissions occur due to no population variable value <br></h1>
</div>
<div id="here-we-see-a-similar-result-with-slightly-positive-trending-between-these-variables-as-we-did-in-base-r-code-below" class="section level1">
<h1>Here, we see a similar result with slightly positive trending between these variables as we did in base R code below</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(continent <span class="op">==</span><span class="st"> &quot;Africa&quot;</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(infant_mortality, life_expectancy, population, country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(population, life_expectancy, <span class="dt">col=</span> country))</code></pre></div>
<pre><code>## Warning: Removed 51 rows containing missing values (geom_point).</code></pre>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="for-our-final-tidyverse-plot-using-ggplot-we-will-pull-out-only-africa-and-year-2000-data-for-a-life_expectancy-as-a-function-of-infant-mortality" class="section level1">
<h1>For our final Tidyverse plot using ggplot(), we will pull out only Africa AND year 2000 data for a life_expectancy as a function of infant mortality<br></h1>
</div>
<div id="we-will-plot-our-points-and-use-the-geom_smooth-function-with-method-set-to-lm-linear-model-to-show-our-best-fit-line." class="section level1">
<h1>We will plot our points and use the geom_smooth() function with method() set to “lm” (linear model) to show our best fit line. <br></h1>
</div>
<div id="the-best-fit-line-helps-visualize-the-negative-correlation-we-saw-accross-all-years-in-african-countries-in-just-the-year-2000-as-well.-the-shadowed-region-around-the-line-is-the-standard-error-range-of-the-linear-model-best-fit-which-is-boolean-se-true-as-a-default-for-ggplot." class="section level1">
<h1>The best fit line helps visualize the negative correlation we saw accross all years in African countries in just the year 2000 as well. The shadowed region around the line is the standard error range of the linear model best fit, which is boolean se = TRUE as a default for ggplot.</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(continent <span class="op">==</span><span class="st"> &quot;Africa&quot;</span>, year <span class="op">==</span><span class="st"> </span><span class="dv">2000</span>) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(infant_mortality, life_expectancy, population, country) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(infant_mortality, life_expectancy)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="kw">geom_smooth</span>(<span class="dt">method =</span> <span class="st">&quot;lm&quot;</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title=</span> <span class="st">&quot;Africa in the year 2000: A best fit line for infant mortality versus life expectancy&quot;</span>)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p><br> <br> <br> #<em>Base R code with original plots from coding exercise 1</em></p>
</div>
<div id="for-base-r---right-of-the-chosen-variable-name-.-all-african-counties-are-accessed-through-the-dataset-gapminder-by-using-the-variable.-the-accessor-is-used-to-access-specific-variables-i.e.-continent-within" class="section level1">
<h1>For base R, &lt;- right of the chosen variable name <br>. All african counties are accessed through the dataset gapminder by using the variable. The accessor $ is used to access specific variables (i.e., continent) within <br></h1>
</div>
<div id="again-in-base-r-we-then-pull-out-the-african-counties-by-using-a-logical-vector-i.e.-to-determine-if-the-variable-content-is-listed-as-africa" class="section level1">
<h1>Again in base R, We then pull out the african counties by using a logical vector (i.e., ==) to determine if the variable content is listed as “Africa” <br></h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">africadata &lt;-<span class="st"> </span>gapminder<span class="op">$</span>continent <span class="op">==</span><span class="st"> &quot;Africa&quot;</span></code></pre></div>
</div>
<div id="str---basic-information-on-the-variable-defined-above" class="section level1">
<h1>str - basic information on the variable defined above</h1>
</div>
<div id="summary---statistical-summaries-of-selected-data" class="section level1">
<h1>summary - statistical summaries of selected data</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(africadata)</code></pre></div>
<pre><code>##  logi [1:10545] FALSE TRUE TRUE FALSE FALSE FALSE ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(africadata)</code></pre></div>
<pre><code>##    Mode   FALSE    TRUE 
## logical    7638    2907</code></pre>
<div id="the-results-from-this-code-chunk-indicated-that-we-have-2907-arguments-that-are-true-out-of-a-total-of-10545.-you-can-see-this-is-the-same-result-as-using-filter-and-select-in-tidyverse." class="section level2">
<h2>the results from this code chunk indicated that we have 2907 arguments that are “true” out of a total of 10545. You can see this is the same result as using filter and select in tidyverse. <br></h2>
</div>
</div>
<div id="for-base-r-we-want-to-define-two-new-variables-1-infant_lifeexpec_africa-which-includes-infant_mortality-and-life_expectency-and-2-pop_lifeexp_africa-includes-population-and-life_expectancy" class="section level1">
<h1>For base R, we want to define two new variables: (1) Infant_LifeExpec_Africa ~ which includes infant_mortality and life_expectency and (2) Pop_LifeExp_Africa ~ includes population and life_expectancy <br></h1>
</div>
<div id="first-lets-pull-out-just-the-infant_mortality-data-from-africa" class="section level1">
<h1>First, lets pull out just the infant_mortality data from africa</h1>
</div>
<div id="in-order-to-do-so-we-call-the-variable-infant_mortality_africa" class="section level1">
<h1>In order to do so, we call the variable infant_mortality_africa</h1>
</div>
<div id="then-we-need-to-access-the-infant-mortality-data-within-gapminder-using-the-accessor-and-applying-the-logical-vector-ie.-africadata.-this-makes-it-so-we-only-pull-the-infant-mortality-data-from-africa" class="section level1">
<h1>Then, we need to access the infant mortality data within gapminder using the $ accessor and applying the logical vector (ie., []) africadata. This makes it so we only pull the infant mortality data from africa</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">infant_mortality_africa &lt;-<span class="st"> </span>gapminder<span class="op">$</span>infant_mortality[africadata]</code></pre></div>
</div>
<div id="lets-apply-the-same-logic-to-pull-out-the-life-expectancy-data" class="section level1">
<h1>Lets apply the same logic to pull out the life expectancy data</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">life_expectency_africa &lt;-<span class="st"> </span>gapminder<span class="op">$</span>life_expectancy[africadata]</code></pre></div>
</div>
<div id="now-we-have-to-seperate-variables-that-we-want-to-combine-to-make-infant_lifeexpec_africa" class="section level1">
<h1>now we have to seperate variables that we want to combine to make Infant_LifeExpec_Africa</h1>
<div id="when-want-to-combine-two-variables-we-use-a-dataframe" class="section level2">
<h2>when want to combine two variables we use a dataframe</h2>
</div>
</div>
<div id="we-need-to-define-the-pieces-of-the-dataframe-by-using-equal-signs-followed-by-the-variables-we-created-earlier.-none-of-this-is-necessary-with-tidyverse." class="section level1">
<h1>We need to define the pieces of the dataframe by using equal signs followed by the variables we created earlier. None of this is necessary with tidyverse.</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Infant_LifeExpec_Africa &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">infant_mortality =</span> infant_mortality_africa, <span class="dt">life_expectancy =</span> life_expectency_africa)</code></pre></div>
</div>
<div id="now-we-need-to-repeat-the-process-with-a-different-set-of-variables-to-create-pop_lifeexp_africa-includes-population-and-life_expectancy" class="section level1">
<h1>Now we need to repeat the process with a different set of variables to create Pop_LifeExp_Africa ~ includes population and life_expectancy</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Population_africa &lt;-<span class="st"> </span>gapminder<span class="op">$</span>population[africadata]
life_expectency_africa &lt;-<span class="st"> </span>gapminder<span class="op">$</span>life_expectancy[africadata]</code></pre></div>
</div>
<div id="create-the-dataframe" class="section level1">
<h1>create the dataframe</h1>
</div>
<div id="remember-to-name-the-dataframe-using--" class="section level1">
<h1>remember to name the dataframe using &lt;-</h1>
</div>
<div id="then-define-parts-of-the-dataframe-using-and-the-dataset" class="section level1">
<h1>then define parts of the dataframe using = and the dataset</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Pop_LifeExp_Africa &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">population =</span> Population_africa, <span class="dt">life_expectency =</span> life_expectency_africa)</code></pre></div>
</div>
<div id="now-lets-check-out-these-new-dataframes-we-made-using-the-str-and-summary-function" class="section level1">
<h1>Now lets check out these new dataframes we made using the str and summary function</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(Pop_LifeExp_Africa)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2907 obs. of  2 variables:
##  $ population     : num  11124892 5270844 2431620 524029 4829291 ...
##  $ life_expectency: num  47.5 36 38.3 50.3 35.2 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(Infant_LifeExpec_Africa)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    2907 obs. of  2 variables:
##  $ infant_mortality: num  148 208 187 116 161 ...
##  $ life_expectancy : num  47.5 36 38.3 50.3 35.2 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(Pop_LifeExp_Africa)</code></pre></div>
<pre><code>##    population        life_expectency
##  Min.   :    41538   Min.   :13.20  
##  1st Qu.:  1605232   1st Qu.:48.23  
##  Median :  5570982   Median :53.98  
##  Mean   : 12235961   Mean   :54.38  
##  3rd Qu.: 13888152   3rd Qu.:60.10  
##  Max.   :182201962   Max.   :77.60  
##  NA&#39;s   :51</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(Infant_LifeExpec_Africa)</code></pre></div>
<pre><code>##  infant_mortality life_expectancy
##  Min.   : 11.40   Min.   :13.20  
##  1st Qu.: 62.20   1st Qu.:48.23  
##  Median : 93.40   Median :53.98  
##  Mean   : 95.12   Mean   :54.38  
##  3rd Qu.:124.70   3rd Qu.:60.10  
##  Max.   :237.40   Max.   :77.60  
##  NA&#39;s   :226</code></pre>
</div>
<div id="we-know-have-two-new-variables-with-2907-rows" class="section level1">
<h1>We know have two new variables with 2907 rows</h1>
</div>
<div id="the-variable-pop_lifeexp_africa-contains-populations-and-life_expectancy-data" class="section level1">
<h1>the variable Pop_LifeExp_Africa contains populations and life_expectancy data</h1>
</div>
<div id="the-variable-infant_lifeexpec_africa-contains-infant-mortaility-and-life_expectancy-data" class="section level1">
<h1>the variable Infant_LifeExpec_Africa contains infant mortaility and life_expectancy data</h1>
</div>
<div id="plotting" class="section level1">
<h1><em>PLOTTING</em></h1>
</div>
<div id="plot-life-expectancy-vs-infant-mortality-for-all-african-countries-using-the-dataframe-you-previously-made" class="section level1">
<h1>plot life expectancy vs infant mortality for all african countries using the dataframe you previously made</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(Infant_LifeExpec_Africa)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-19-1.png" width="672" /> #the plot indicates a negative correlation between the two variables ##Countires with increased infant mortality show a decrease in life expectancy</p>
</div>
<div id="plot-population-vs-life-expectancy-for-all-african-countries" class="section level1">
<h1>Plot population vs life expectancy for all african countries</h1>
</div>
<div id="we-need-to-convert-population-to-a-log10-function-first.-in-order-to-do-so-we-should-created-a-new-variable-which-holds-the-population-data-in-log10-form" class="section level1">
<h1>we need to convert population to a log10 function first. In order to do so we should created a new variable which holds the population data in log10 form</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">logten_pop_africa &lt;-<span class="st"> </span><span class="kw">log10</span>(Population_africa)</code></pre></div>
</div>
<div id="we-now-need-to-create-a-new-datafram-with-the-population-at-log10-scale" class="section level1">
<h1>we now need to create a new datafram with the population at log10 scale</h1>
</div>
<div id="list-the-variable-you-want-on-the-x-asix-first-i.e.-log10-population" class="section level1">
<h1>list the variable you want on the x-asix first (i.e., log10 population)</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">log10_pop_life_expec_africa &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">population =</span> logten_pop_africa, <span class="dt">life_expectancy =</span> life_expectency_africa)</code></pre></div>
</div>
<div id="now-we-can-plot-it" class="section level1">
<h1>now we can plot it</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(log10_pop_life_expec_africa)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-22-1.png" width="672" /> #this plot shows streaks of data that appear to go together. By looking at this streaks i believe that they show the different countries in africa. They also seem to move in a positive trend.</p>
</div>
<div id="more-data-processing" class="section level1">
<h1><em>MORE DATA PROCESSING</em></h1>
</div>
<div id="which-years-have-missing-infant-mortality-data" class="section level1">
<h1>which years have missing infant mortality data</h1>
</div>
<div id="in-order-to-determine-this-i-am-creating-a-variable-for-the-na-values" class="section level1">
<h1>In order to determine this i am creating a variable for the NA values</h1>
</div>
<div id="i-will-used-the-is-comand-to-pull-the-na-values" class="section level1">
<h1>i will used the is comand to pull the na values</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">na_index &lt;-<span class="st"> </span><span class="kw">is.na</span>(infant_mortality_africa)</code></pre></div>
</div>
<div id="now-i-am-applying-the-na_index-to-the-gapminder-year-data-to-see-which-ones-are-na" class="section level1">
<h1>now i am applying the na_index to the gapminder year data to see which ones are na</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">gapminder<span class="op">$</span>year[na_index]</code></pre></div>
<pre><code>##   [1] 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960
##  [15] 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960
##  [29] 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960
##  [43] 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1960 1961
##  [57] 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961
##  [71] 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961
##  [85] 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961 1961
##  [99] 1961 1961 1961 1961 1961 1961 1961 1961 1962 1962 1962 1962 1962 1962
## [113] 1962 1962 1962 1962 1962 1962 1962 1962 1962 1962 1962 1962 1962 1962
## [127] 1962 1962 1962 1962 1962 1962 1962 1962 1962 1963 1963 1963 1963 1963
## [141] 1963 1963 1963 1963 1963 1963 1963 1963 1963 1963 1963 1963 1963 1963
## [155] 1963 1963 1963 1963 1964 1964 1964 1964 1964 1964 1964 1964 1964 1964
## [169] 1964 1964 1965 1965 1965 1965 1965 1975 1975 1975 1975 1975 1975 1975
## [183] 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975
## [197] 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975
## [211] 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975
## [225] 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1975 1976
## [239] 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976
## [253] 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976
## [267] 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976
## [281] 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976 1976
## [295] 1976 1976 1976 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977
## [309] 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977
## [323] 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977 1977
## [337] 1977 1977 1977 1977 1977 1977 1977 1977 1978 1978 1978 1978 1978 1978
## [351] 1978 1978 1978 1978 1978 1978 1978 1978 1978 1978 1978 1978 1978 1978
## [365] 1978 1978 1978 1979 1979 1979 1979 1979 1979 1979 1979 1979 1979 1979
## [379] 1979 1979 1979 1979 1979 1979 1979 1979 1979 1979 1979 1980 1980 1980
## [393] 1980 1980 1980 1980 1980 1980 1981 1981 1981 1991 1991 1991 1991 1991
## [407] 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991
## [421] 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991
## [435] 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991
## [449] 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991
## [463] 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991 1991
## [477] 1991 1991 1991 1991 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992
## [491] 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992
## [505] 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992
## [519] 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992 1992
## [533] 1992 1992 1992 1992 1992 1992 1993 1993 1993 1993 1993 1993 1993 1993
## [547] 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993
## [561] 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993 1993
## [575] 1993 1993 1993 1993 1993 1994 1994 1994 1994 1994 1994 1994 1994 1994
## [589] 1994 1994 1994 1994 1994 1994 1994 1994 1994 1994 1994 1995 1995 1995
## [603] 1995 1995 1995 1995 1995 1995 1995 1995 1995 1995 1995 1995 1995 1995
## [617] 1995 1995 1996 1996 1996 1996 1996 1996 1996 1997 1997 2006 2006 2006
## [631] 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006 2006
## [645] 2006 2006 2006 2006 2006 2006 2006 2006 2007 2007 2007 2007 2007 2007
## [659] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007
## [673] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007
## [687] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007
## [701] 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007 2007
## [715] 2007 2007 2007 2007 2007 2007 2007 2007 2008 2008 2008 2008 2008 2008
## [729] 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008
## [743] 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008
## [757] 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008 2008
## [771] 2008 2008 2008 2008 2008 2008 2008 2008 2009 2009 2009 2009 2009 2009
## [785] 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009
## [799] 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2009 2010 2010
## [813] 2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 2010 2010
## [827] 2010 2010 2010 2010 2010 2011 2011 2011 2011 2011 2011 2011 2011 2011
## [841] 2011 2011 2011 2011 2011 2011 2011 2012 2012 2012 2012 2012 2013</code></pre>
</div>
<div id="we-now-see-a-list-of-years-where-infant-mortality-data-is-missing." class="section level1">
<h1>we now see a list of years where infant mortality data is missing.</h1>
</div>
<div id="some-years-are-repeated.-this-means-that-multiple-countries-are-missing-those-years-in-africa" class="section level1">
<h1>some years are repeated. This means that multiple countries are missing those years in Africa</h1>
</div>
<div id="in-order-to-see-the-total-number-of-na-values-in-the-variable-na_index-we-can-use-the-sum-function" class="section level1">
<h1>in order to see the total number of NA values in the variable Na_index, we can use the sum function</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">sum</span>(na_index)</code></pre></div>
<pre><code>## [1] 226</code></pre>
</div>
<div id="there-are-226-which-matches-what-was-given-in-our-exercise" class="section level1">
<h1>there are 226, which matches what was given in our exercise</h1>
</div>
<div id="now-we-want-to-extract-the-data-for-only-the-year-2000-from-africadata" class="section level1">
<h1>Now we want to extract the data for only the year 2000 from africadata</h1>
</div>
<div id="remember-that-africadata-contains-9-variables" class="section level1">
<h1>remember that africadata contains 9 variables</h1>
</div>
<div id="first-lets-create-an-index-to-select-for-the-year-2000" class="section level1">
<h1>first lets create an index to select for the year 2000</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> yr2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>year <span class="op">==</span><span class="st"> </span><span class="dv">2000</span></code></pre></div>
</div>
<div id="now-we-want-to-use-the-logical-operator-since-we-want-two-things-to-be-true-i.e.-from-africa-data-and-the-year-2000" class="section level1">
<h1>Now we want to use the logical operator &amp; since we want two things to be true (i.e., from africa data AND the year 2000)</h1>
</div>
<div id="we-will-call-this-new-variable-africa2000" class="section level1">
<h1>We will call this new variable africa2000</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">africa2000 &lt;-<span class="st"> </span>yr2000 <span class="op">&amp;</span><span class="st"> </span>africadata</code></pre></div>
</div>
<div id="now-we-need-to-apply-this-index-to-all-nine-variable-in-the-dataset-to-pull-out-the-data-for-the-year-2000-in-only-african-countries" class="section level1">
<h1>Now we need to apply this index to all NINE variable in the dataset to pull out the data for the year 2000 in only african countries</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">year2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>year[africa2000]
region2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>region[africa2000]
country2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>country[africa2000]
infant_mortality2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>infant_mortality[africa2000]
life_expectency2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>life_expectancy[africa2000]
fertility2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>fertility[africa2000]
gdp2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>gdp[africa2000]
continent2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>continent[africa2000]
population2000 &lt;-<span class="st"> </span>gapminder<span class="op">$</span>population[africa2000]</code></pre></div>
</div>
<div id="phew-pulled-them-all-out" class="section level1">
<h1>phew, pulled them all out</h1>
</div>
<div id="now-we-need-to-create-a-new-dataframe-using-all-the-new-variable-names-we-created-above-that-single-out-african-countries-in-the-year-2000" class="section level1">
<h1>now we need to create a new dataframe using all the new variable names we created above that single out african countries in the year 2000</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">africa2000_df &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">year =</span> year2000, <span class="dt">region =</span> region2000, <span class="dt">country =</span> country2000, <span class="dt">infant_mortality =</span> infant_mortality2000, <span class="dt">life_expectency =</span> life_expectency2000, <span class="dt">fertility =</span> fertility2000, <span class="dt">gdp =</span> gdp2000, <span class="dt">continent=</span> continent2000, <span class="dt">population =</span> population2000)</code></pre></div>
</div>
<div id="now-check-the-data-using-str-and-summary" class="section level1">
<h1>now check the data using str and summary</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">str</span>(africa2000_df)</code></pre></div>
<pre><code>## &#39;data.frame&#39;:    51 obs. of  9 variables:
##  $ year            : int  2000 2000 2000 2000 2000 2000 2000 2000 2000 2000 ...
##  $ region          : Factor w/ 22 levels &quot;Australia and New Zealand&quot;,..: 11 10 20 17 20 5 10 20 10 10 ...
##  $ country         : Factor w/ 185 levels &quot;Albania&quot;,&quot;Algeria&quot;,..: 2 3 18 22 26 27 29 31 32 33 ...
##  $ infant_mortality: num  33.9 128.3 89.3 52.4 96.2 ...
##  $ life_expectency : num  73.3 52.3 57.2 47.6 52.6 46.7 54.3 68.4 45.3 51.5 ...
##  $ fertility       : num  2.51 6.84 5.98 3.41 6.59 7.06 5.62 3.7 5.45 7.35 ...
##  $ gdp             : num  5.48e+10 9.13e+09 2.25e+09 5.63e+09 2.61e+09 ...
##  $ continent       : Factor w/ 5 levels &quot;Africa&quot;,&quot;Americas&quot;,..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ population      : num  31183658 15058638 6949366 1736579 11607944 ...</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(africa2000_df)</code></pre></div>
<pre><code>##       year                            region           country  
##  Min.   :2000   Eastern Africa           :16   Algeria     : 1  
##  1st Qu.:2000   Western Africa           :16   Angola      : 1  
##  Median :2000   Middle Africa            : 8   Benin       : 1  
##  Mean   :2000   Northern Africa          : 6   Botswana    : 1  
##  3rd Qu.:2000   Southern Africa          : 5   Burkina Faso: 1  
##  Max.   :2000   Australia and New Zealand: 0   Burundi     : 1  
##                 (Other)                  : 0   (Other)     :45  
##  infant_mortality life_expectency   fertility          gdp           
##  Min.   : 12.30   Min.   :37.60   Min.   :1.990   Min.   :2.019e+08  
##  1st Qu.: 60.80   1st Qu.:51.75   1st Qu.:4.150   1st Qu.:1.274e+09  
##  Median : 80.30   Median :54.30   Median :5.550   Median :3.238e+09  
##  Mean   : 78.93   Mean   :56.36   Mean   :5.156   Mean   :1.155e+10  
##  3rd Qu.:103.30   3rd Qu.:60.00   3rd Qu.:5.960   3rd Qu.:8.654e+09  
##  Max.   :143.30   Max.   :75.00   Max.   :7.730   Max.   :1.329e+11  
##                                                                      
##     continent    population       
##  Africa  :51   Min.   :    81154  
##  Americas: 0   1st Qu.:  2304687  
##  Asia    : 0   Median :  8799165  
##  Europe  : 0   Mean   : 15659800  
##  Oceania : 0   3rd Qu.: 17391242  
##                Max.   :122876723  
## </code></pre>
</div>
<div id="we-have-51-observation-and-9-variables" class="section level1">
<h1>we have 51 observation and 9 variables</h1>
</div>
<div id="more-plotting" class="section level1">
<h1><em>MORE PLOTTING</em></h1>
</div>
<div id="now-we-are-going-to-make-the-two-previous-plots-again-however-only-using-the-data-from-the-year-2000" class="section level1">
<h1>Now we are going to make the two previous plots again, however only using the data from the year 2000</h1>
</div>
<div id="first-lets-plot-infant-mortality-and-life-expectency-in-africa-for-the-yr-2000" class="section level1">
<h1>first lets plot infant mortality and life expectency in africa for the yr 2000</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(infant_mortality2000, life_expectency2000)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-31-1.png" width="672" /> #we see a negative correlation</p>
</div>
<div id="plot-population-size-and-life-expectancy-for-the-year-2000-in-africa" class="section level1">
<h1>plot population size and life expectancy for the year 2000 in africa</h1>
</div>
<div id="first-define-the-population-to-a-log10-scale" class="section level1">
<h1>first define the population to a log10 scale</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">log10pop_yr2000 &lt;-<span class="st"> </span><span class="kw">log10</span>(population2000)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(log10pop_yr2000, life_expectency2000)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-33-1.png" width="672" /> #no noticeable correlation</p>
</div>
<div id="a-simple-fit" class="section level1">
<h1>A SIMPLE FIT</h1>
</div>
<div id="use-the-lm-function-linear-model-function---used-to-create-a-simple-regression-model-and-fit-life-expectancy-at-the-outcome-y-variable-and-infant-mortality-as-the-predictor-x-variable" class="section level1">
<h1>Use the lm function (linear model function - used to create a simple regression model) and fit life expectancy at the outcome (y variable), and infant mortality as the predictor (x variable)</h1>
</div>
<div id="the-summary-function-gives-us-various-statistics-indlucding-residuals-coefficents" class="section level1">
<h1>the summary function gives us various statistics indlucding residuals, coefficents,</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm1 &lt;-<span class="st"> </span><span class="kw">lm</span>(life_expectency2000 <span class="op">~</span><span class="st"> </span>infant_mortality2000)
<span class="kw">summary</span>(lm1)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = life_expectency2000 ~ infant_mortality2000)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -22.6651  -3.7087   0.9914   4.0408   8.6817 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)          71.29331    2.42611  29.386  &lt; 2e-16 ***
## infant_mortality2000 -0.18916    0.02869  -6.594 2.83e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 6.221 on 49 degrees of freedom
## Multiple R-squared:  0.4701, Adjusted R-squared:  0.4593 
## F-statistic: 43.48 on 1 and 49 DF,  p-value: 2.826e-08</code></pre>
</div>
<div id="linear-regression-model-for-life-expectancy-y-and-population-size-as-the-predictor" class="section level1">
<h1>linear regression model for life expectancy (y) and population size as the predictor</h1>
</div>
<div id="a-p-value-of-2.826e-08-suggests-that-these-are-related-as-the-p-value-is-very-small" class="section level1">
<h1>a p value of 2.826e-08 suggests that these are related as the P value is very small</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lm2 &lt;-<span class="st"> </span><span class="kw">lm</span>(life_expectency2000 <span class="op">~</span><span class="st"> </span>log10pop_yr2000)
<span class="kw">summary</span>(lm2)</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = life_expectency2000 ~ log10pop_yr2000)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -19.113  -4.809  -1.554   3.907  18.863 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)       65.324     12.520   5.217 3.65e-06 ***
## log10pop_yr2000   -1.315      1.829  -0.719    0.476    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 8.502 on 49 degrees of freedom
## Multiple R-squared:  0.01044,    Adjusted R-squared:  -0.009755 
## F-statistic: 0.517 on 1 and 49 DF,  p-value: 0.4755</code></pre>
</div>
<div id="p-value-of-0.4755.-a-p-value-this-size-suggests-the-variables-are-not-related-i.e.-population-size-does-not-affect-life-expectancy" class="section level1">
<h1>P value of 0.4755. A p value this size suggests the variables are not related (i.e., population size does not affect life expectancy)</h1>
</div>
<div id="we-can-also-visualise-this-fit-line-on-the-scatterplot-using-the-abline-function" class="section level1">
<h1>we can also visualise this fit line on the scatterplot using the abline function</h1>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(infant_mortality2000, life_expectency2000)
<span class="kw">abline</span>(lm1)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-36-1.png" width="672" /> #this is nice because it resolidifies the conclusions i came to before</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>(log10pop_yr2000, life_expectency2000)
<span class="kw">abline</span>(lm2)</code></pre></div>
<p><img src="MeganBeaudry_Coding_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
